using UXDivers.Grial;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eleos3.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Eleos3.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string StringGrial {
            get {
                return ResourceManager.GetString("StringGrial", resourceCulture);
            }
        }
        
        internal static string StringUIKIT {
            get {
                return ResourceManager.GetString("StringUIKIT", resourceCulture);
            }
        }
        
        internal static string StringColon {
            get {
                return ResourceManager.GetString("StringColon", resourceCulture);
            }
        }
        
        internal static string StringNew {
            get {
                return ResourceManager.GetString("StringNew", resourceCulture);
            }
        }
        
        internal static string StringOK {
            get {
                return ResourceManager.GetString("StringOK", resourceCulture);
            }
        }
        
        internal static string StringSave {
            get {
                return ResourceManager.GetString("StringSave", resourceCulture);
            }
        }
        
        internal static string StringCompare {
            get {
                return ResourceManager.GetString("StringCompare", resourceCulture);
            }
        }
        
        internal static string StringShare {
            get {
                return ResourceManager.GetString("StringShare", resourceCulture);
            }
        }
        
        internal static string StringBuy {
            get {
                return ResourceManager.GetString("StringBuy", resourceCulture);
            }
        }
        
        internal static string StringUsername {
            get {
                return ResourceManager.GetString("StringUsername", resourceCulture);
            }
        }
        
        internal static string StringName {
            get {
                return ResourceManager.GetString("StringName", resourceCulture);
            }
        }
        
        internal static string StringLastName {
            get {
                return ResourceManager.GetString("StringLastName", resourceCulture);
            }
        }
        
        internal static string StringCardNumber {
            get {
                return ResourceManager.GetString("StringCardNumber", resourceCulture);
            }
        }
        
        internal static string StringCVC {
            get {
                return ResourceManager.GetString("StringCVC", resourceCulture);
            }
        }
        
        internal static string StringExpirationDate {
            get {
                return ResourceManager.GetString("StringExpirationDate", resourceCulture);
            }
        }
        
        internal static string StringAddress {
            get {
                return ResourceManager.GetString("StringAddress", resourceCulture);
            }
        }
        
        internal static string StringAddress1 {
            get {
                return ResourceManager.GetString("StringAddress1", resourceCulture);
            }
        }
        
        internal static string StringAddress2 {
            get {
                return ResourceManager.GetString("StringAddress2", resourceCulture);
            }
        }
        
        internal static string StringCity {
            get {
                return ResourceManager.GetString("StringCity", resourceCulture);
            }
        }
        
        internal static string StringState {
            get {
                return ResourceManager.GetString("StringState", resourceCulture);
            }
        }
        
        internal static string StringZipCode {
            get {
                return ResourceManager.GetString("StringZipCode", resourceCulture);
            }
        }
        
        internal static string StringCountry {
            get {
                return ResourceManager.GetString("StringCountry", resourceCulture);
            }
        }
        
        internal static string StringNotes {
            get {
                return ResourceManager.GetString("StringNotes", resourceCulture);
            }
        }
        
        internal static string StringEmail {
            get {
                return ResourceManager.GetString("StringEmail", resourceCulture);
            }
        }
        
        internal static string StringExplore {
            get {
                return ResourceManager.GetString("StringExplore", resourceCulture);
            }
        }
        
        internal static string StringPassword {
            get {
                return ResourceManager.GetString("StringPassword", resourceCulture);
            }
        }
        
        internal static string StringSignUp {
            get {
                return ResourceManager.GetString("StringSignUp", resourceCulture);
            }
        }
        
        internal static string StringLogin {
            get {
                return ResourceManager.GetString("StringLogin", resourceCulture);
            }
        }
        
        internal static string StringWelcomeToGrial {
            get {
                return ResourceManager.GetString("StringWelcomeToGrial", resourceCulture);
            }
        }
        
        internal static string StringTwitter {
            get {
                return ResourceManager.GetString("StringTwitter", resourceCulture);
            }
        }
        
        internal static string StringFacebook {
            get {
                return ResourceManager.GetString("StringFacebook", resourceCulture);
            }
        }
        
        internal static string StringSend {
            get {
                return ResourceManager.GetString("StringSend", resourceCulture);
            }
        }
        
        internal static string StringDone {
            get {
                return ResourceManager.GetString("StringDone", resourceCulture);
            }
        }
        
        internal static string StringConfirmation {
            get {
                return ResourceManager.GetString("StringConfirmation", resourceCulture);
            }
        }
        
        internal static string StringError {
            get {
                return ResourceManager.GetString("StringError", resourceCulture);
            }
        }
        
        internal static string StringNotification {
            get {
                return ResourceManager.GetString("StringNotification", resourceCulture);
            }
        }
        
        internal static string StringSuccess {
            get {
                return ResourceManager.GetString("StringSuccess", resourceCulture);
            }
        }
        
        internal static string StringWarning {
            get {
                return ResourceManager.GetString("StringWarning", resourceCulture);
            }
        }
        
        internal static string StringScreens {
            get {
                return ResourceManager.GetString("StringScreens", resourceCulture);
            }
        }
        
        internal static string StringCategorySocial {
            get {
                return ResourceManager.GetString("StringCategorySocial", resourceCulture);
            }
        }
        
        internal static string StringCategoryArticles {
            get {
                return ResourceManager.GetString("StringCategoryArticles", resourceCulture);
            }
        }
        
        internal static string StringCategoryDashboards {
            get {
                return ResourceManager.GetString("StringCategoryDashboards", resourceCulture);
            }
        }
        
        internal static string StringCategoryNavigation {
            get {
                return ResourceManager.GetString("StringCategoryNavigation", resourceCulture);
            }
        }
        
        internal static string StringCategoryLogins {
            get {
                return ResourceManager.GetString("StringCategoryLogins", resourceCulture);
            }
        }
        
        internal static string StringCategoryForms {
            get {
                return ResourceManager.GetString("StringCategoryForms", resourceCulture);
            }
        }
        
        internal static string StringCategoryECommerce {
            get {
                return ResourceManager.GetString("StringCategoryECommerce", resourceCulture);
            }
        }
        
        internal static string StringCategoryWalkthroughs {
            get {
                return ResourceManager.GetString("StringCategoryWalkthroughs", resourceCulture);
            }
        }
        
        internal static string StringCategoryOnboarding {
            get {
                return ResourceManager.GetString("StringCategoryOnboarding", resourceCulture);
            }
        }
        
        internal static string StringCategoryMessages {
            get {
                return ResourceManager.GetString("StringCategoryMessages", resourceCulture);
            }
        }
        
        internal static string StringCategoryTheme {
            get {
                return ResourceManager.GetString("StringCategoryTheme", resourceCulture);
            }
        }
        
        internal static string StringCategoryDataViz {
            get {
                return ResourceManager.GetString("StringCategoryDataViz", resourceCulture);
            }
        }
        
        internal static string StringClareJapi {
            get {
                return ResourceManager.GetString("StringClareJapi", resourceCulture);
            }
        }
        
        internal static string StringRobertStainford {
            get {
                return ResourceManager.GetString("StringRobertStainford", resourceCulture);
            }
        }
        
        internal static string StringNext {
            get {
                return ResourceManager.GetString("StringNext", resourceCulture);
            }
        }
        
        internal static string StringPrevious {
            get {
                return ResourceManager.GetString("StringPrevious", resourceCulture);
            }
        }
        
        internal static string StringFinish {
            get {
                return ResourceManager.GetString("StringFinish", resourceCulture);
            }
        }
        
        internal static string StringLinkedin {
            get {
                return ResourceManager.GetString("StringLinkedin", resourceCulture);
            }
        }
        
        internal static string StringContact {
            get {
                return ResourceManager.GetString("StringContact", resourceCulture);
            }
        }
        
        internal static string StringContactUs {
            get {
                return ResourceManager.GetString("StringContactUs", resourceCulture);
            }
        }
        
        internal static string StringEditContact {
            get {
                return ResourceManager.GetString("StringEditContact", resourceCulture);
            }
        }
        
        internal static string StringNewContact {
            get {
                return ResourceManager.GetString("StringNewContact", resourceCulture);
            }
        }
        
        internal static string StringLoading {
            get {
                return ResourceManager.GetString("StringLoading", resourceCulture);
            }
        }
        
        internal static string StringSkip {
            get {
                return ResourceManager.GetString("StringSkip", resourceCulture);
            }
        }
        
        internal static string StringSaveChanges {
            get {
                return ResourceManager.GetString("StringSaveChanges", resourceCulture);
            }
        }
        
        internal static string StringBatmanChoice {
            get {
                return ResourceManager.GetString("StringBatmanChoice", resourceCulture);
            }
        }
        
        internal static string StringExtraSoftUIFlavor {
            get {
                return ResourceManager.GetString("StringExtraSoftUIFlavor", resourceCulture);
            }
        }
        
        internal static string StringImpressYourBoss {
            get {
                return ResourceManager.GetString("StringImpressYourBoss", resourceCulture);
            }
        }
        
        internal static string StringIcons {
            get {
                return ResourceManager.GetString("StringIcons", resourceCulture);
            }
        }
        
        internal static string StringContextActionTapped {
            get {
                return ResourceManager.GetString("StringContextActionTapped", resourceCulture);
            }
        }
        
        internal static string StringTappedOnContextAction {
            get {
                return ResourceManager.GetString("StringTappedOnContextAction", resourceCulture);
            }
        }
        
        internal static string StringMessageTapped {
            get {
                return ResourceManager.GetString("StringMessageTapped", resourceCulture);
            }
        }
        
        internal static string StringButtonTapped {
            get {
                return ResourceManager.GetString("StringButtonTapped", resourceCulture);
            }
        }
        
        internal static string StringTappedOnAuthorMessage {
            get {
                return ResourceManager.GetString("StringTappedOnAuthorMessage", resourceCulture);
            }
        }
        
        internal static string StringMoreFrom {
            get {
                return ResourceManager.GetString("StringMoreFrom", resourceCulture);
            }
        }
        
        internal static string StringLastMonth {
            get {
                return ResourceManager.GetString("StringLastMonth", resourceCulture);
            }
        }
        
        internal static string StringLastYear {
            get {
                return ResourceManager.GetString("StringLastYear", resourceCulture);
            }
        }
        
        internal static string StringLastWeek {
            get {
                return ResourceManager.GetString("StringLastWeek", resourceCulture);
            }
        }
        
        internal static string StringRelatedNews {
            get {
                return ResourceManager.GetString("StringRelatedNews", resourceCulture);
            }
        }
        
        internal static string StringAll {
            get {
                return ResourceManager.GetString("StringAll", resourceCulture);
            }
        }
        
        internal static string StringInTransit {
            get {
                return ResourceManager.GetString("StringInTransit", resourceCulture);
            }
        }
        
        internal static string StringClosed {
            get {
                return ResourceManager.GetString("StringClosed", resourceCulture);
            }
        }
        
        internal static string StringClose {
            get {
                return ResourceManager.GetString("StringClose", resourceCulture);
            }
        }
        
        internal static string StringOpen {
            get {
                return ResourceManager.GetString("StringOpen", resourceCulture);
            }
        }
        
        internal static string StringScore {
            get {
                return ResourceManager.GetString("StringScore", resourceCulture);
            }
        }
        
        internal static string RemainingTasks {
            get {
                return ResourceManager.GetString("RemainingTasks", resourceCulture);
            }
        }
        
        internal static string AgendaTitle {
            get {
                return ResourceManager.GetString("AgendaTitle", resourceCulture);
            }
        }
        
        internal static string CompletedTasks {
            get {
                return ResourceManager.GetString("CompletedTasks", resourceCulture);
            }
        }
        
        internal static string StringWorkspaces {
            get {
                return ResourceManager.GetString("StringWorkspaces", resourceCulture);
            }
        }
        
        internal static string StringProjects {
            get {
                return ResourceManager.GetString("StringProjects", resourceCulture);
            }
        }
        
        internal static string StringDetails {
            get {
                return ResourceManager.GetString("StringDetails", resourceCulture);
            }
        }
        
        internal static string PageTitleParallaxHeaderArticle {
            get {
                return ResourceManager.GetString("PageTitleParallaxHeaderArticle", resourceCulture);
            }
        }
        
        internal static string PageTitleCardArticle {
            get {
                return ResourceManager.GetString("PageTitleCardArticle", resourceCulture);
            }
        }
        
        internal static string PageTitleCurvedHeaderArticle {
            get {
                return ResourceManager.GetString("PageTitleCurvedHeaderArticle", resourceCulture);
            }
        }
        
        internal static string PageTitleArticlesClassicView {
            get {
                return ResourceManager.GetString("PageTitleArticlesClassicView", resourceCulture);
            }
        }
        
        internal static string PageTitleArticlesFeed {
            get {
                return ResourceManager.GetString("PageTitleArticlesFeed", resourceCulture);
            }
        }
        
        internal static string PageTitleArticlesList {
            get {
                return ResourceManager.GetString("PageTitleArticlesList", resourceCulture);
            }
        }
        
        internal static string PageTitleArticlesListVariant {
            get {
                return ResourceManager.GetString("PageTitleArticlesListVariant", resourceCulture);
            }
        }
        
        internal static string PageTitleArticlesColumns {
            get {
                return ResourceManager.GetString("PageTitleArticlesColumns", resourceCulture);
            }
        }
        
        internal static string PageTitleArticleDetail {
            get {
                return ResourceManager.GetString("PageTitleArticleDetail", resourceCulture);
            }
        }
        
        internal static string PageTitleDashboardCards {
            get {
                return ResourceManager.GetString("PageTitleDashboardCards", resourceCulture);
            }
        }
        
        internal static string PageTitleFlatDashboard {
            get {
                return ResourceManager.GetString("PageTitleFlatDashboard", resourceCulture);
            }
        }
        
        internal static string PageTitleDashboardMultipleTiles {
            get {
                return ResourceManager.GetString("PageTitleDashboardMultipleTiles", resourceCulture);
            }
        }
        
        internal static string PageTitleIconsDashboard {
            get {
                return ResourceManager.GetString("PageTitleIconsDashboard", resourceCulture);
            }
        }
        
        internal static string PageTitleImagesDashboard {
            get {
                return ResourceManager.GetString("PageTitleImagesDashboard", resourceCulture);
            }
        }
        
        internal static string RoundedLabelCast {
            get {
                return ResourceManager.GetString("RoundedLabelCast", resourceCulture);
            }
        }
        
        internal static string RoundedLabelDirector {
            get {
                return ResourceManager.GetString("RoundedLabelDirector", resourceCulture);
            }
        }
        
        internal static string AlertTitleMovieTapped {
            get {
                return ResourceManager.GetString("AlertTitleMovieTapped", resourceCulture);
            }
        }
        
        internal static string AlertMessageMovieShouldPlayMovieNow {
            get {
                return ResourceManager.GetString("AlertMessageMovieShouldPlayMovieNow", resourceCulture);
            }
        }
        
        internal static string SampleDashboardGrialMovies {
            get {
                return ResourceManager.GetString("SampleDashboardGrialMovies", resourceCulture);
            }
        }
        
        internal static string ButtonPlayMovie {
            get {
                return ResourceManager.GetString("ButtonPlayMovie", resourceCulture);
            }
        }
        
        internal static string PageTitleChatMain {
            get {
                return ResourceManager.GetString("PageTitleChatMain", resourceCulture);
            }
        }
        
        internal static string PageTitleChatMessages {
            get {
                return ResourceManager.GetString("PageTitleChatMessages", resourceCulture);
            }
        }
        
        internal static string PageTitleAddContact {
            get {
                return ResourceManager.GetString("PageTitleAddContact", resourceCulture);
            }
        }
        
        internal static string PageTitleContactDetail {
            get {
                return ResourceManager.GetString("PageTitleContactDetail", resourceCulture);
            }
        }
        
        internal static string PageTitleContactSimpleDetail {
            get {
                return ResourceManager.GetString("PageTitleContactSimpleDetail", resourceCulture);
            }
        }
        
        internal static string PageTitleDocumentTimeline {
            get {
                return ResourceManager.GetString("PageTitleDocumentTimeline", resourceCulture);
            }
        }
        
        internal static string PageTitleProfile {
            get {
                return ResourceManager.GetString("PageTitleProfile", resourceCulture);
            }
        }
        
        internal static string SampleUserProfile {
            get {
                return ResourceManager.GetString("SampleUserProfile", resourceCulture);
            }
        }
        
        internal static string PageTitleSocial {
            get {
                return ResourceManager.GetString("PageTitleSocial", resourceCulture);
            }
        }
        
        internal static string PageTitleSocialVariant {
            get {
                return ResourceManager.GetString("PageTitleSocialVariant", resourceCulture);
            }
        }
        
        internal static string PageTitleSocialCard {
            get {
                return ResourceManager.GetString("PageTitleSocialCard", resourceCulture);
            }
        }
        
        internal static string PageTitleTimeline {
            get {
                return ResourceManager.GetString("PageTitleTimeline", resourceCulture);
            }
        }
        
        internal static string PageTitleSocialGalleryImagePreview {
            get {
                return ResourceManager.GetString("PageTitleSocialGalleryImagePreview", resourceCulture);
            }
        }
        
        internal static string StringFriends {
            get {
                return ResourceManager.GetString("StringFriends", resourceCulture);
            }
        }
        
        internal static string StringPhotos {
            get {
                return ResourceManager.GetString("StringPhotos", resourceCulture);
            }
        }
        
        internal static string PageTitleCheckout {
            get {
                return ResourceManager.GetString("PageTitleCheckout", resourceCulture);
            }
        }
        
        internal static string PageTitleEcommerceMain {
            get {
                return ResourceManager.GetString("PageTitleEcommerceMain", resourceCulture);
            }
        }
        
        internal static string PageTitleOrderConfirmation {
            get {
                return ResourceManager.GetString("PageTitleOrderConfirmation", resourceCulture);
            }
        }
        
        internal static string PageTitleProductDetail {
            get {
                return ResourceManager.GetString("PageTitleProductDetail", resourceCulture);
            }
        }
        
        internal static string ButtonAddToCart {
            get {
                return ResourceManager.GetString("ButtonAddToCart", resourceCulture);
            }
        }
        
        internal static string PageTitleProductsCatalog {
            get {
                return ResourceManager.GetString("PageTitleProductsCatalog", resourceCulture);
            }
        }
        
        internal static string PageTitleProductItemFullScreen {
            get {
                return ResourceManager.GetString("PageTitleProductItemFullScreen", resourceCulture);
            }
        }
        
        internal static string PageTitleProductImageFullScreen {
            get {
                return ResourceManager.GetString("PageTitleProductImageFullScreen", resourceCulture);
            }
        }
        
        internal static string SampleProductFullscreen {
            get {
                return ResourceManager.GetString("SampleProductFullscreen", resourceCulture);
            }
        }
        
        internal static string PageTitleProductOrder {
            get {
                return ResourceManager.GetString("PageTitleProductOrder", resourceCulture);
            }
        }
        
        internal static string PageTitleProductsGrid {
            get {
                return ResourceManager.GetString("PageTitleProductsGrid", resourceCulture);
            }
        }
        
        internal static string PageTitleProductsGridVariant {
            get {
                return ResourceManager.GetString("PageTitleProductsGridVariant", resourceCulture);
            }
        }
        
        internal static string BannerTitle25DiscOff {
            get {
                return ResourceManager.GetString("BannerTitle25DiscOff", resourceCulture);
            }
        }
        
        internal static string BannerBodyEnjoyItNow {
            get {
                return ResourceManager.GetString("BannerBodyEnjoyItNow", resourceCulture);
            }
        }
        
        internal static string PageTitleProductItemView {
            get {
                return ResourceManager.GetString("PageTitleProductItemView", resourceCulture);
            }
        }
        
        internal static string SampleProductItemView {
            get {
                return ResourceManager.GetString("SampleProductItemView", resourceCulture);
            }
        }
        
        internal static string SampleProductCarousel {
            get {
                return ResourceManager.GetString("SampleProductCarousel", resourceCulture);
            }
        }
        
        internal static string PageTitleProductsCarousel {
            get {
                return ResourceManager.GetString("PageTitleProductsCarousel", resourceCulture);
            }
        }
        
        internal static string PageTitleTabbedLogin {
            get {
                return ResourceManager.GetString("PageTitleTabbedLogin", resourceCulture);
            }
        }
        
        internal static string PageTitleFullBackgroundLogin {
            get {
                return ResourceManager.GetString("PageTitleFullBackgroundLogin", resourceCulture);
            }
        }
        
        internal static string PageTitleFullBackgroundSignup {
            get {
                return ResourceManager.GetString("PageTitleFullBackgroundSignup", resourceCulture);
            }
        }
        
        internal static string PageTitleOrganizationForm {
            get {
                return ResourceManager.GetString("PageTitleOrganizationForm", resourceCulture);
            }
        }
        
        internal static string PageTitleSimpleLogin {
            get {
                return ResourceManager.GetString("PageTitleSimpleLogin", resourceCulture);
            }
        }
        
        internal static string PageTitleSimpleSignUp {
            get {
                return ResourceManager.GetString("PageTitleSimpleSignUp", resourceCulture);
            }
        }
        
        internal static string PageTitlePasswordRecovery {
            get {
                return ResourceManager.GetString("PageTitlePasswordRecovery", resourceCulture);
            }
        }
        
        internal static string PageTitleLogin {
            get {
                return ResourceManager.GetString("PageTitleLogin", resourceCulture);
            }
        }
        
        internal static string PageTitleSignUp {
            get {
                return ResourceManager.GetString("PageTitleSignUp", resourceCulture);
            }
        }
        
        internal static string LabelUseCredentialsToLogin {
            get {
                return ResourceManager.GetString("LabelUseCredentialsToLogin", resourceCulture);
            }
        }
        
        internal static string LabelOrConnectWith {
            get {
                return ResourceManager.GetString("LabelOrConnectWith", resourceCulture);
            }
        }
        
        internal static string LabelForgotYourPassword {
            get {
                return ResourceManager.GetString("LabelForgotYourPassword", resourceCulture);
            }
        }
        
        internal static string LabelForgotYourPasswordExplained {
            get {
                return ResourceManager.GetString("LabelForgotYourPasswordExplained", resourceCulture);
            }
        }
        
        internal static string ErrorPleaseEnterValidEmail {
            get {
                return ResourceManager.GetString("ErrorPleaseEnterValidEmail", resourceCulture);
            }
        }
        
        internal static string LabelLoginOrRegisterUsinMailOrPass {
            get {
                return ResourceManager.GetString("LabelLoginOrRegisterUsinMailOrPass", resourceCulture);
            }
        }
        
        internal static string LabelRegisterNow {
            get {
                return ResourceManager.GetString("LabelRegisterNow", resourceCulture);
            }
        }
        
        internal static string LabelRegisterNowAndEnjoy {
            get {
                return ResourceManager.GetString("LabelRegisterNowAndEnjoy", resourceCulture);
            }
        }
        
        internal static string LabelPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("LabelPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        internal static string LabelRepeatPassword {
            get {
                return ResourceManager.GetString("LabelRepeatPassword", resourceCulture);
            }
        }
        
        internal static string ButtonAlreadyUserLoginNow {
            get {
                return ResourceManager.GetString("ButtonAlreadyUserLoginNow", resourceCulture);
            }
        }
        
        internal static string PageTitlePopups {
            get {
                return ResourceManager.GetString("PageTitlePopups", resourceCulture);
            }
        }
        
        internal static string PageTitleChatTimeline {
            get {
                return ResourceManager.GetString("PageTitleChatTimeline", resourceCulture);
            }
        }
        
        internal static string PageTitleRecentChatList {
            get {
                return ResourceManager.GetString("PageTitleRecentChatList", resourceCulture);
            }
        }
        
        internal static string PageTitleMessagesList {
            get {
                return ResourceManager.GetString("PageTitleMessagesList", resourceCulture);
            }
        }
        
        internal static string PageTitleChatMessagesList {
            get {
                return ResourceManager.GetString("PageTitleChatMessagesList", resourceCulture);
            }
        }
        
        internal static string LabelThereIsNothingHere {
            get {
                return ResourceManager.GetString("LabelThereIsNothingHere", resourceCulture);
            }
        }
        
        internal static string PageTitleNavigationCardsDescriptionList {
            get {
                return ResourceManager.GetString("PageTitleNavigationCardsDescriptionList", resourceCulture);
            }
        }
        
        internal static string PageTitleMoviesMain {
            get {
                return ResourceManager.GetString("PageTitleMoviesMain", resourceCulture);
            }
        }
        
        internal static string PageTitleFeaturedMovies {
            get {
                return ResourceManager.GetString("PageTitleFeaturedMovies", resourceCulture);
            }
        }
        
        internal static string PageTitleMovieDetail {
            get {
                return ResourceManager.GetString("PageTitleMovieDetail", resourceCulture);
            }
        }
        
        internal static string PageTitleArticlesBrowser {
            get {
                return ResourceManager.GetString("PageTitleArticlesBrowser", resourceCulture);
            }
        }
        
        internal static string PageTitleDashboardCarousel {
            get {
                return ResourceManager.GetString("PageTitleDashboardCarousel", resourceCulture);
            }
        }
        
        internal static string PageTitleMainMenu {
            get {
                return ResourceManager.GetString("PageTitleMainMenu", resourceCulture);
            }
        }
        
        internal static string PageTitleNavigationCardsList {
            get {
                return ResourceManager.GetString("PageTitleNavigationCardsList", resourceCulture);
            }
        }
        
        internal static string PageTitleNavigationFlatList {
            get {
                return ResourceManager.GetString("PageTitleNavigationFlatList", resourceCulture);
            }
        }
        
        internal static string PageTitleNavigationListWithIcons {
            get {
                return ResourceManager.GetString("PageTitleNavigationListWithIcons", resourceCulture);
            }
        }
        
        internal static string PageTitleNavigationListWithImages {
            get {
                return ResourceManager.GetString("PageTitleNavigationListWithImages", resourceCulture);
            }
        }
        
        internal static string PageTitleEmptyState {
            get {
                return ResourceManager.GetString("PageTitleEmptyState", resourceCulture);
            }
        }
        
        internal static string PageTitleNotifications {
            get {
                return ResourceManager.GetString("PageTitleNotifications", resourceCulture);
            }
        }
        
        internal static string StringReadyMadeUIsForXamarin {
            get {
                return ResourceManager.GetString("StringReadyMadeUIsForXamarin", resourceCulture);
            }
        }
        
        internal static string PageTitleWelcome {
            get {
                return ResourceManager.GetString("PageTitleWelcome", resourceCulture);
            }
        }
        
        internal static string LabelTakeYourAppToNextLevel {
            get {
                return ResourceManager.GetString("LabelTakeYourAppToNextLevel", resourceCulture);
            }
        }
        
        internal static string LabelWelcomeToGrialStarter {
            get {
                return ResourceManager.GetString("LabelWelcomeToGrialStarter", resourceCulture);
            }
        }
        
        internal static string LabelWelcomeToGrialStarterDescription {
            get {
                return ResourceManager.GetString("LabelWelcomeToGrialStarterDescription", resourceCulture);
            }
        }
        
        internal static string TakeWalkThrough {
            get {
                return ResourceManager.GetString("TakeWalkThrough", resourceCulture);
            }
        }
        
        internal static string PageTitleVideoCarouselHighlights {
            get {
                return ResourceManager.GetString("PageTitleVideoCarouselHighlights", resourceCulture);
            }
        }
        
        internal static string PageTitleWalkthroughGradient {
            get {
                return ResourceManager.GetString("PageTitleWalkthroughGradient", resourceCulture);
            }
        }
        
        internal static string PageTitleWalkthroughIllustration {
            get {
                return ResourceManager.GetString("PageTitleWalkthroughIllustration", resourceCulture);
            }
        }
        
        internal static string PageTitleWalkthroughImage {
            get {
                return ResourceManager.GetString("PageTitleWalkthroughImage", resourceCulture);
            }
        }
        
        internal static string PageTitleWalkthroughMinimal {
            get {
                return ResourceManager.GetString("PageTitleWalkthroughMinimal", resourceCulture);
            }
        }
        
        internal static string PageTitleWalkthroughFlat {
            get {
                return ResourceManager.GetString("PageTitleWalkthroughFlat", resourceCulture);
            }
        }
        
        internal static string PageTitleWalkthrough {
            get {
                return ResourceManager.GetString("PageTitleWalkthrough", resourceCulture);
            }
        }
        
        internal static string PageTitleWalkthroughVariant {
            get {
                return ResourceManager.GetString("PageTitleWalkthroughVariant", resourceCulture);
            }
        }
        
        internal static string SampleTitleWalkthrough {
            get {
                return ResourceManager.GetString("SampleTitleWalkthrough", resourceCulture);
            }
        }
        
        internal static string SampleTitleWalkthroughFlat {
            get {
                return ResourceManager.GetString("SampleTitleWalkthroughFlat", resourceCulture);
            }
        }
        
        internal static string SampleTitleWalkthroughVariant {
            get {
                return ResourceManager.GetString("SampleTitleWalkthroughVariant", resourceCulture);
            }
        }
        
        internal static string WalkthroughHeaderLearn {
            get {
                return ResourceManager.GetString("WalkthroughHeaderLearn", resourceCulture);
            }
        }
        
        internal static string WalkthroughHeaderSaveTime {
            get {
                return ResourceManager.GetString("WalkthroughHeaderSaveTime", resourceCulture);
            }
        }
        
        internal static string WalkthroughHeaderWelcome {
            get {
                return ResourceManager.GetString("WalkthroughHeaderWelcome", resourceCulture);
            }
        }
        
        internal static string WalkthroughTextLearn {
            get {
                return ResourceManager.GetString("WalkthroughTextLearn", resourceCulture);
            }
        }
        
        internal static string WalkthroughTextSaveTime {
            get {
                return ResourceManager.GetString("WalkthroughTextSaveTime", resourceCulture);
            }
        }
        
        internal static string WalkthroughTextWelcome {
            get {
                return ResourceManager.GetString("WalkthroughTextWelcome", resourceCulture);
            }
        }
        
        internal static string PageTitleThemeOverview {
            get {
                return ResourceManager.GetString("PageTitleThemeOverview", resourceCulture);
            }
        }
        
        internal static string StringAnimation {
            get {
                return ResourceManager.GetString("StringAnimation", resourceCulture);
            }
        }
        
        internal static string PageTitleTabControlCustomSample {
            get {
                return ResourceManager.GetString("PageTitleTabControlCustomSample", resourceCulture);
            }
        }
        
        internal static string PageTitleTabControlAndroidSample {
            get {
                return ResourceManager.GetString("PageTitleTabControlAndroidSample", resourceCulture);
            }
        }
        
        internal static string PageTitleTabControliOSSample {
            get {
                return ResourceManager.GetString("PageTitleTabControliOSSample", resourceCulture);
            }
        }
        
        internal static string PageTitleTabControlBottomPlacementSample {
            get {
                return ResourceManager.GetString("PageTitleTabControlBottomPlacementSample", resourceCulture);
            }
        }
        
        internal static string PageTitleTab {
            get {
                return ResourceManager.GetString("PageTitleTab", resourceCulture);
            }
        }
        
        internal static string SampleTitleThemeDemoSettings {
            get {
                return ResourceManager.GetString("SampleTitleThemeDemoSettings", resourceCulture);
            }
        }
        
        internal static string PageTitleAbout {
            get {
                return ResourceManager.GetString("PageTitleAbout", resourceCulture);
            }
        }
        
        internal static string PageTitleGenericAbout {
            get {
                return ResourceManager.GetString("PageTitleGenericAbout", resourceCulture);
            }
        }
        
        internal static string PageTitleRichAbout {
            get {
                return ResourceManager.GetString("PageTitleRichAbout", resourceCulture);
            }
        }
        
        internal static string PageTitleCustomSettings {
            get {
                return ResourceManager.GetString("PageTitleCustomSettings", resourceCulture);
            }
        }
        
        internal static string PageTitleCustomActivityIndicator {
            get {
                return ResourceManager.GetString("PageTitleCustomActivityIndicator", resourceCulture);
            }
        }
        
        internal static string PageTitleResponsiveHelpers {
            get {
                return ResourceManager.GetString("PageTitleResponsiveHelpers", resourceCulture);
            }
        }
        
        internal static string PageTitleNativeControls {
            get {
                return ResourceManager.GetString("PageTitleNativeControls", resourceCulture);
            }
        }
        
        internal static string PageTitleCustomRenderers {
            get {
                return ResourceManager.GetString("PageTitleCustomRenderers", resourceCulture);
            }
        }
        
        internal static string PageTitleCommonViews {
            get {
                return ResourceManager.GetString("PageTitleCommonViews", resourceCulture);
            }
        }
        
        internal static string PageTitleSettings {
            get {
                return ResourceManager.GetString("PageTitleSettings", resourceCulture);
            }
        }
        
        internal static string LabelDisplayGlobalIssues {
            get {
                return ResourceManager.GetString("LabelDisplayGlobalIssues", resourceCulture);
            }
        }
        
        internal static string LabelClearImageCache {
            get {
                return ResourceManager.GetString("LabelClearImageCache", resourceCulture);
            }
        }
        
        internal static string LabelActivityIndicators {
            get {
                return ResourceManager.GetString("LabelActivityIndicators", resourceCulture);
            }
        }
        
        internal static string LabelButtons {
            get {
                return ResourceManager.GetString("LabelButtons", resourceCulture);
            }
        }
        
        internal static string LabelFrames {
            get {
                return ResourceManager.GetString("LabelFrames", resourceCulture);
            }
        }
        
        internal static string LabelThisIsAFrameDescription {
            get {
                return ResourceManager.GetString("LabelThisIsAFrameDescription", resourceCulture);
            }
        }
        
        internal static string LabelEntriesAndEditors {
            get {
                return ResourceManager.GetString("LabelEntriesAndEditors", resourceCulture);
            }
        }
        
        internal static string LabelPlaceholderEmail {
            get {
                return ResourceManager.GetString("LabelPlaceholderEmail", resourceCulture);
            }
        }
        
        internal static string EditorSampleText {
            get {
                return ResourceManager.GetString("EditorSampleText", resourceCulture);
            }
        }
        
        internal static string LabelSliders {
            get {
                return ResourceManager.GetString("LabelSliders", resourceCulture);
            }
        }
        
        internal static string LabelProgressBars {
            get {
                return ResourceManager.GetString("LabelProgressBars", resourceCulture);
            }
        }
        
        internal static string LabelSwitches {
            get {
                return ResourceManager.GetString("LabelSwitches", resourceCulture);
            }
        }
        
        internal static string LabelPickers {
            get {
                return ResourceManager.GetString("LabelPickers", resourceCulture);
            }
        }
        
        internal static string PickerTitleSample {
            get {
                return ResourceManager.GetString("PickerTitleSample", resourceCulture);
            }
        }
        
        internal static string LabelListViewAndSearchBar {
            get {
                return ResourceManager.GetString("LabelListViewAndSearchBar", resourceCulture);
            }
        }
        
        internal static string SearchBarPlaceholderSearchForAName {
            get {
                return ResourceManager.GetString("SearchBarPlaceholderSearchForAName", resourceCulture);
            }
        }
        
        internal static string ButtonDefault {
            get {
                return ResourceManager.GetString("ButtonDefault", resourceCulture);
            }
        }
        
        internal static string ButtonPrimaryAction {
            get {
                return ResourceManager.GetString("ButtonPrimaryAction", resourceCulture);
            }
        }
        
        internal static string ButtonSecondaryAction {
            get {
                return ResourceManager.GetString("ButtonSecondaryAction", resourceCulture);
            }
        }
        
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        internal static string ButtonMore {
            get {
                return ResourceManager.GetString("ButtonMore", resourceCulture);
            }
        }
        
        internal static string ButtonAddComment {
            get {
                return ResourceManager.GetString("ButtonAddComment", resourceCulture);
            }
        }
        
        internal static string LabelArtinaButtons {
            get {
                return ResourceManager.GetString("LabelArtinaButtons", resourceCulture);
            }
        }
        
        internal static string LabelCircleImages {
            get {
                return ResourceManager.GetString("LabelCircleImages", resourceCulture);
            }
        }
        
        internal static string LabelArtinaEntry {
            get {
                return ResourceManager.GetString("LabelArtinaEntry", resourceCulture);
            }
        }
        
        internal static string LabelValidationEntryErrorStyle {
            get {
                return ResourceManager.GetString("LabelValidationEntryErrorStyle", resourceCulture);
            }
        }
        
        internal static string StringSomethingWrongHere {
            get {
                return ResourceManager.GetString("StringSomethingWrongHere", resourceCulture);
            }
        }
        
        internal static string ValidationErrorEnterRequiredInfo {
            get {
                return ResourceManager.GetString("ValidationErrorEnterRequiredInfo", resourceCulture);
            }
        }
        
        internal static string ValidationWarningOops {
            get {
                return ResourceManager.GetString("ValidationWarningOops", resourceCulture);
            }
        }
        
        internal static string StringYourAccount {
            get {
                return ResourceManager.GetString("StringYourAccount", resourceCulture);
            }
        }
        
        internal static string StringConnectYourAccount {
            get {
                return ResourceManager.GetString("StringConnectYourAccount", resourceCulture);
            }
        }
        
        internal static string ImageCellDetailDaysLoggedIn {
            get {
                return ResourceManager.GetString("ImageCellDetailDaysLoggedIn", resourceCulture);
            }
        }
        
        internal static string EntryCellSampleEmail {
            get {
                return ResourceManager.GetString("EntryCellSampleEmail", resourceCulture);
            }
        }
        
        internal static string EntryCellPlaceholderPhoneNumber {
            get {
                return ResourceManager.GetString("EntryCellPlaceholderPhoneNumber", resourceCulture);
            }
        }
        
        internal static string LabelBrandBlock {
            get {
                return ResourceManager.GetString("LabelBrandBlock", resourceCulture);
            }
        }
        
        internal static string LabelBadge {
            get {
                return ResourceManager.GetString("LabelBadge", resourceCulture);
            }
        }
        
        internal static string LabelRoundedLabel {
            get {
                return ResourceManager.GetString("LabelRoundedLabel", resourceCulture);
            }
        }
        
        internal static string RoundedLabelTextSample {
            get {
                return ResourceManager.GetString("RoundedLabelTextSample", resourceCulture);
            }
        }
        
        internal static string LabelAboutUsText {
            get {
                return ResourceManager.GetString("LabelAboutUsText", resourceCulture);
            }
        }
        
        internal static string OurHistoryString {
            get {
                return ResourceManager.GetString("OurHistoryString", resourceCulture);
            }
        }
        
        internal static string OurHistoryStringLongText {
            get {
                return ResourceManager.GetString("OurHistoryStringLongText", resourceCulture);
            }
        }
        
        internal static string LabelWeAreATeamOfPassionate {
            get {
                return ResourceManager.GetString("LabelWeAreATeamOfPassionate", resourceCulture);
            }
        }
        
        internal static string LabelOurProducts {
            get {
                return ResourceManager.GetString("LabelOurProducts", resourceCulture);
            }
        }
        
        internal static string LabelOurProductsLongText {
            get {
                return ResourceManager.GetString("LabelOurProductsLongText", resourceCulture);
            }
        }
        
        internal static string LabelSpecialThanks {
            get {
                return ResourceManager.GetString("LabelSpecialThanks", resourceCulture);
            }
        }
        
        internal static string LabelCredits {
            get {
                return ResourceManager.GetString("LabelCredits", resourceCulture);
            }
        }
        
        internal static string TabItemTextFriends {
            get {
                return ResourceManager.GetString("TabItemTextFriends", resourceCulture);
            }
        }
        
        internal static string StringHelloClare {
            get {
                return ResourceManager.GetString("StringHelloClare", resourceCulture);
            }
        }
        
        internal static string StringNoPendingTasksToday {
            get {
                return ResourceManager.GetString("StringNoPendingTasksToday", resourceCulture);
            }
        }
        
        internal static string ButtonDeleteAccount {
            get {
                return ResourceManager.GetString("ButtonDeleteAccount", resourceCulture);
            }
        }
        
        internal static string PageTitleEmployeePerformanceDashboard {
            get {
                return ResourceManager.GetString("PageTitleEmployeePerformanceDashboard", resourceCulture);
            }
        }
        
        internal static string PageTitleEmployeeProfileDashboard {
            get {
                return ResourceManager.GetString("PageTitleEmployeeProfileDashboard", resourceCulture);
            }
        }
        
        internal static string PageTitlePerformanceDashboard {
            get {
                return ResourceManager.GetString("PageTitlePerformanceDashboard", resourceCulture);
            }
        }
        
        internal static string PageTitlePerformanceDashboardMain {
            get {
                return ResourceManager.GetString("PageTitlePerformanceDashboardMain", resourceCulture);
            }
        }
        
        internal static string PageTitleShippingDetail {
            get {
                return ResourceManager.GetString("PageTitleShippingDetail", resourceCulture);
            }
        }
        
        internal static string PageTitleTaskBrowser {
            get {
                return ResourceManager.GetString("PageTitleTaskBrowser", resourceCulture);
            }
        }
        
        internal static string PageTitleTaskOverview {
            get {
                return ResourceManager.GetString("PageTitleTaskOverview", resourceCulture);
            }
        }
        
        internal static string PageTitleEmployeeForm {
            get {
                return ResourceManager.GetString("PageTitleEmployeeForm", resourceCulture);
            }
        }
        
        internal static string FlowTitleEcommerce {
            get {
                return ResourceManager.GetString("FlowTitleEcommerce", resourceCulture);
            }
        }
        
        internal static string FlowTitleTasks {
            get {
                return ResourceManager.GetString("FlowTitleTasks", resourceCulture);
            }
        }
        
        internal static string FlowTitleMovies {
            get {
                return ResourceManager.GetString("FlowTitleMovies", resourceCulture);
            }
        }
        
        internal static string FlowTitleMessages {
            get {
                return ResourceManager.GetString("FlowTitleMessages", resourceCulture);
            }
        }
        
        internal static string RichAboutPageDescriptionString {
            get {
                return ResourceManager.GetString("RichAboutPageDescriptionString", resourceCulture);
            }
        }
        
        internal static string RichAboutPageMissionString {
            get {
                return ResourceManager.GetString("RichAboutPageMissionString", resourceCulture);
            }
        }
        
        internal static string RichAboutPageMission2String {
            get {
                return ResourceManager.GetString("RichAboutPageMission2String", resourceCulture);
            }
        }
        
        internal static string RichAboutPageFollowUs {
            get {
                return ResourceManager.GetString("RichAboutPageFollowUs", resourceCulture);
            }
        }
        
        internal static string RichAboutPageEagerToHear {
            get {
                return ResourceManager.GetString("RichAboutPageEagerToHear", resourceCulture);
            }
        }
        
        internal static string StringAboutUs {
            get {
                return ResourceManager.GetString("StringAboutUs", resourceCulture);
            }
        }
        
        internal static string StringOurMission {
            get {
                return ResourceManager.GetString("StringOurMission", resourceCulture);
            }
        }
        
        internal static string StringOurTeam {
            get {
                return ResourceManager.GetString("StringOurTeam", resourceCulture);
            }
        }
        
        internal static string MovieDetails {
            get {
                return ResourceManager.GetString("MovieDetails", resourceCulture);
            }
        }
        
        internal static string TeamMember {
            get {
                return ResourceManager.GetString("TeamMember", resourceCulture);
            }
        }
        
        internal static string TasksPerformance {
            get {
                return ResourceManager.GetString("TasksPerformance", resourceCulture);
            }
        }
        
        internal static string StringTotal {
            get {
                return ResourceManager.GetString("StringTotal", resourceCulture);
            }
        }
        
        internal static string ShippingAddress {
            get {
                return ResourceManager.GetString("ShippingAddress", resourceCulture);
            }
        }
        
        internal static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        internal static string BuyIt {
            get {
                return ResourceManager.GetString("BuyIt", resourceCulture);
            }
        }
        
        internal static string StringSubtotal {
            get {
                return ResourceManager.GetString("StringSubtotal", resourceCulture);
            }
        }
        
        internal static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        internal static string OrderWithGift {
            get {
                return ResourceManager.GetString("OrderWithGift", resourceCulture);
            }
        }
        
        internal static string RelatedProducts {
            get {
                return ResourceManager.GetString("RelatedProducts", resourceCulture);
            }
        }
        
        internal static string SeeMoreComments {
            get {
                return ResourceManager.GetString("SeeMoreComments", resourceCulture);
            }
        }
        
        internal static string SeeLessComments {
            get {
                return ResourceManager.GetString("SeeLessComments", resourceCulture);
            }
        }
        
        internal static string ProceedToCheckout {
            get {
                return ResourceManager.GetString("ProceedToCheckout", resourceCulture);
            }
        }
        
        internal static string ConfirmOrder {
            get {
                return ResourceManager.GetString("ConfirmOrder", resourceCulture);
            }
        }
        
        internal static string OrderPlacedNotification {
            get {
                return ResourceManager.GetString("OrderPlacedNotification", resourceCulture);
            }
        }
        
        internal static string StringContacts {
            get {
                return ResourceManager.GetString("StringContacts", resourceCulture);
            }
        }
        
        internal static string StringMessages {
            get {
                return ResourceManager.GetString("StringMessages", resourceCulture);
            }
        }
        
        internal static string TypeYourMessage {
            get {
                return ResourceManager.GetString("TypeYourMessage", resourceCulture);
            }
        }
        
        internal static string StringEdit {
            get {
                return ResourceManager.GetString("StringEdit", resourceCulture);
            }
        }
        
        internal static string StringHome {
            get {
                return ResourceManager.GetString("StringHome", resourceCulture);
            }
        }
        
        internal static string StringMobile {
            get {
                return ResourceManager.GetString("StringMobile", resourceCulture);
            }
        }
        
        internal static string StringMessage {
            get {
                return ResourceManager.GetString("StringMessage", resourceCulture);
            }
        }
        
        internal static string PageTitleWelcomeStarter {
            get {
                return ResourceManager.GetString("PageTitleWelcomeStarter", resourceCulture);
            }
        }
        
        internal static string StringRetry {
            get {
                return ResourceManager.GetString("StringRetry", resourceCulture);
            }
        }
    }
}
